# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9fecc0122c5233ecdf948e692aaf829fafdbb4809739d30664b14fa37c674cc25d697a3b846be426cc064ec189b991e9f8e3ca70031e2bcb2c8d46db58e8491

test:
  secret_key_base: 61547052fbb7a90986025f15098a7be1ef5c21f7c6895ca6449b197493e4ae74d201792c1e0ab386649822f79714b3eefb99c8762314e075eb1b54f86d3e60f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
